### ISSUE TITLE
GUI - seek problem 2 

### ISSUE THREAD

**Issue by Addalin** [Addalin/cameranetwork#42]
**Describe the bug**
seek button trouble relates to #28 

**To Reproduce**
1. seek tab 
2. click on  : update dates --> chose data --> fore read (True) --> Query --> chose time to show (pick HDR) --> push seek
5. See error
```
Server cam_116L raised an error
===============================

Calling the cmd handler caused an error:
Traceback (most recent call last):
  File "C:\Users\addalin\Dropbox\cloud CT\cameranetwork\CameraNetwork\server.py", line 414, in _on_request
    answer = yield cb(*args, **kwds)
  File "C:\ProgramData\Anaconda2\envs\cn_client\lib\site-packages\tornado\gen.py", line 1055, in run
    value = future.result()
  File "C:\ProgramData\Anaconda2\envs\cn_client\lib\site-packages\tornado\concurrent.py", line 238, in result
    raise_exc_info(self._exc_info)
  File "C:\ProgramData\Anaconda2\envs\cn_client\lib\site-packages\tornado\gen.py", line 292, in wrapper
    result = func(*args, **kwargs)
  File "C:\Users\addalin\Dropbox\cloud CT\cameranetwork\CameraNetwork\server.py", line 992, in handle_seek
    timedelta_threshold=timedelta_threshold
  File "C:\Users\addalin\Dropbox\cloud CT\cameranetwork\CameraNetwork\controller.py", line 1381, in seekImageArray
    ignore_date_extrinsic
  File "C:\Users\addalin\Dropbox\cloud CT\cameranetwork\CameraNetwork\controller.py", line 1490, in preprocess_array
    img_array = self._vignetting.applyVignetting(img_array)
AttributeError: 'Controller' object has no attribute '_vignetting'
```

**Expected behavior**
Show images of the expected time

**Screenshots**
![image](https://user-images.githubusercontent.com/9436237/66269662-a0d8c080-e853-11e9-8cc5-1160f3d61d28.png)

**Comment by Addalin** [comment]
Currently, this error mainly accrues when start_local.py is running on windows. 
When running on VISL we don't get this error anymore. 
This is either environment or pandas version issue, as in #28.
