### ISSUE TITLE
SSH-->Putty in GUI

### ISSUE THREAD

**Issue by OmerShubi** [Addalin/cameranetwork#46]
**Describe the bug**
GUI Crashes on putty click
```
2019-10-22 19:06:28,009 [MainThread  ] [DEBUG]  sending message from:<CameraNetwork.gui.main.ServerModel object at 0x7f0808088dd0>
Traceback (most recent call last):
  File "/home/shubi/.conda/envs/cn_client/lib/python2.7/site-packages/enaml/qt/q_deferred_caller.py", line 42, in customEvent
    event.callback(*event.args, **event.kwargs)
  File "/home/shubi/PycharmProjects/cameranetwork/CameraNetwork/gui/main.py", line 1682, in receive_message
    self.servers_dict[server_id].handle_reply(status, cmd, args, kwds)
  File "/home/shubi/PycharmProjects/cameranetwork/CameraNetwork/gui/main.py", line 1977, in handle_reply
    cb(*args, **kwds)
  File "/home/shubi/PycharmProjects/cameranetwork/CameraNetwork/gui/main.py", line 1993, in reply_tunnel_details
    subprocess.Popen(putty_cmd)
  File "/home/shubi/.conda/envs/cn_client/lib/python2.7/subprocess.py", line 394, in __init__
    errread, errwrite)
  File "/home/shubi/.conda/envs/cn_client/lib/python2.7/subprocess.py", line 1047, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory
```
**To Reproduce**
1. Go to GUI
2. Click on camera_id
3. Scroll down to SSH-->Putty

**Expected behavior**
open terminal with camera

**Desktop (please complete the following information):**
 - OS: linux

**Comment by OmerShubi** [comment]
Maybe because from linux environment? or maybe because parameters? what file /directory is missing? Need to check

**Comment by Addalin** [comment]
On windows:

10.17 ‘NETWORK ERROR: CONNECTION REFUSED’
This error means that the network connection PuTTY tried to make to your server was rejected by the server. Usually this happens because the server does not provide the service which PuTTY is trying to access.

Check that you are connecting with the correct protocol (SSH, Telnet or Rlogin), and check that the port number is correct. If that fails, consult the administrator of your server
