### ISSUE TITLE
Torndo ioloop – uses jitter as handle and not float/int

### ISSUE THREAD

**Issue by OmerShubi** [Addalin/cameranetwork#5]
Exectuing `/home/shubi/PycharmProjects/cameranetwork/scripts_client/camera_client.py` 
results in (line 111)
https://github.com/Addalin/cameranetwork/blob/645b5ce298d7efc78b29de20adfdc44d50f1d015/CameraNetwork/client.py#L108-L114
 throwing the following error 
```python
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/home/shubi/.conda/envs/cvenv2.7/lib/python2.7/threading.py", line 801, in __bootstrap_inner
    self.run()
  File "/home/shubi/.conda/envs/cvenv2.7/lib/python2.7/threading.py", line 754, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/home/shubi/PycharmProjects/cameranetwork/CameraNetwork/client.py", line 112, in start
    partial(self.send_mmi, service=MDP.MMI_SERVICES, msg=[]), self.mmi_period, self.loop
  File "/home/shubi/.conda/envs/cvenv2.7/lib/python2.7/site-packages/tornado/ioloop.py", line 1209, in start
    self._schedule_next()
  File "/home/shubi/.conda/envs/cvenv2.7/lib/python2.7/site-packages/tornado/ioloop.py", line 1237, in _schedule_next
    self._update_next(self.io_loop.time())
  File "/home/shubi/.conda/envs/cvenv2.7/lib/python2.7/site-packages/tornado/ioloop.py", line 1244, in _update_next
    callback_time_sec *= 1 + (self.jitter * (random.random() - 0.5))
TypeError: unsupported operand type(s) for *: 'ZMQIOLoop' and 'float'

```

**Comment by OmerShubi** [comment]
Working solution:
`conda install tornado=4.5.3`

https://github.com/jupyter/notebook/issues/3407#issue-303235000
