### ISSUE TITLE
gui crash on pressing data

### ISSUE THREAD

**Issue by OmerShubi** [Addalin/cameranetwork#6]
to reproduce pressin servers>camera_id>status>Data button in gui

```python
2019-09-03 17:56:39,869 [MainThread  ] [DEBUG]  sending message from:<CameraNetwork.gui.main.ServerModel object at 0x7f5e6c9e7200>
Traceback (most recent call last):
  File "/home/shubi/.conda/envs/cvenv2.7/lib/python2.7/site-packages/enaml/qt/qt_abstract_button.py", line 77, in on_clicked
    self.declaration.clicked(checked)
  File "/home/shubi/.conda/envs/cvenv2.7/lib/python2.7/site-packages/enaml/core/declarative_meta.py", line 68, in declarative_change_handler
    engine.write(owner, change['name'], change)
  File "/home/shubi/.conda/envs/cvenv2.7/lib/python2.7/site-packages/enaml/core/expression_engine.py", line 217, in write
    pair.writer(owner, name, change)
  File "/home/shubi/.conda/envs/cvenv2.7/lib/python2.7/site-packages/enaml/core/standard_handlers.py", line 82, in __call__
    call_func(func, (), {}, scope)
  File "/home/shubi/PycharmProjects/cameranetwork/CameraNetwork/gui/enaml_files/docks.enaml", line 107, in f
    popup = MsgDataPopup(msg_data=server_model.reply_data).show()
NameError: name 'MsgDataPopup' is not defined
Aborted (core dumped)

```

**Comment by Addalin** [comment]
@scaperex what does it suppose to do? add a screenshot.

**Comment by OmerShubi** [comment]
@Addalin  I think 30d96c8 solves this I can't reproduce the bug and pressing on data now works. 
For exmaple, after pressing on settings, which sends the get_settings command to the camera, pressing on data results in 
![Screenshot from 2019-10-22 19-19-48](https://user-images.githubusercontent.com/28459495/67307353-0c33bb00-f501-11e9-9baf-aa93f658871d.png)
in addition to the popup that showed (not shown in picture).

**Comment by OmerShubi** [comment]
Closing this issue for now
