### ISSUE TITLE
TypeError: only size-1 arrays can be converted to Python scalars

### ISSUE THREAD

**Issue by OmerShubi** [Addalin/cameranetwork#8]
In client gui: Arrays&rarr;Capture Settings&rarr;Capture
```<!-- language: lang-none -->
2019-09-04 14:00:46,922 [MainThread  ] [DEBUG]  Creating the 3D map view.
2019-09-04 14:00:46,923 [MainThread  ] [DEBUG]  Clearing 3D view.
2019-09-04 14:00:47,041 [MainThread  ] [DEBUG]  Threading the map projection.
Exception in thread Thread-2:
Traceback (most recent call last):
  File "/home/shubi/.conda/envs/cvenv2.7/lib/python2.7/threading.py", line 801, in __bootstrap_inner
    self.run()
  File "/home/shubi/.conda/envs/cvenv2.7/lib/python2.7/threading.py", line 754, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/home/shubi/PycharmProjects/cameranetwork/CameraNetwork/gui/main.py", line 185, in createMapProjection
    alt0=alt0,
  File "/home/shubi/PycharmProjects/cameranetwork/CameraNetwork/visualization.py", line 97, in convertMapData
    lat0=lat0, lon0=lon0, h0=alt0)
  File "/home/shubi/.conda/envs/cvenv2.7/lib/python2.7/site-packages/pymap3d/math/ned.py", line 225, in geodetic2ned
    e, n, u = geodetic2enu(lat, lon, h, lat0, lon0, h0, ell, deg=deg)
  File "/home/shubi/.conda/envs/cvenv2.7/lib/python2.7/site-packages/pymap3d/math/enu.py", line 169, in geodetic2enu
    x1, y1, z1 = geodetic2ecef(lat, lon, h, ell, deg=deg)
  File "/home/shubi/.conda/envs/cvenv2.7/lib/python2.7/site-packages/pymap3d/math/ecef.py", line 47, in geodetic2ecef
    lat = radians(lat)
TypeError: only size-1 arrays can be converted to Python scalars

2019-09-04 14:00:47,234 [MainThread  ] [DEBUG]  Drawing the 3D Grid.
2019-09-04 14:00:47,268 [MainThread  ] [DEBUG]  Broadcasting message: array
2019-09-04 14:00:49,297 [MainThread  ] [INFO ]  Creating new item for server 236
2019-09-04 14:00:49,308 [MainThread  ] [DEBUG]  32.775776 35.024963 229.0 2019-09-04 11:00:47.363374
2019-09-04 14:00:49,309 [MainThread  ] [DEBUG]  Sun altitude 58:09:51.2, azimuth 221:02:47.7 at time 2019-09-04 11:00:47.363374
2019-09-04 14:00:49,309 [MainThread  ] [DEBUG]  32.775776 35.024963 229.0 2019-09-04 11:00:47.363374
2019-09-04 14:00:49,309 [MainThread  ] [DEBUG]  Sun altitude 58:09:51.2, azimuth 221:02:47.7 at time 2019-09-04 11:00:47.363374
Creating default grid 2D
Updating the GRID_ECEF
2019-09-04 14:00:49,320 [MainThread  ] [INFO ]  Adding new view of server 236
2019-09-04 14:00:49,658 [MainThread  ] [DEBUG]  Initializing the sun position: [[115.53807505 110.35075685]].
2019-09-04 14:00:49,661 [MainThread  ] [DEBUG]  Arrays LOS updated. Will update the map.
2019-09-04 14:00:49,662 [MainThread  ] [DEBUG]  Creating the LOS vectors.
2019-09-04 14:01:10,691 [MainThread  ] [INFO ]  Calculating LOS.
2019-09-04 14:01:10,692 [MainThread  ] [DEBUG]  Arrays LOS updated. Will update the map.
```

**Comment by OmerShubi** [comment]
[The failing function (pymap3d-ecef-geodetic2ecef) docs](https://scivision.github.io/pymap3d/ecef.html#pymap3d.ecef.geodetic2ecef)

**Comment by OmerShubi** [comment]
Simultaneously in the GUI log traceback:
```
Server 236 raised an error
==========================

Calling the cmd handler caused an error:
Traceback (most recent call last):
  File "/home/odroid/code/cameranetwork/CameraNetwork/server.py", line 414, in _on_request
    answer = yield cb(*args, **kwds)
  File "/usr/local/lib/python2.7/dist-packages/tornado/gen.py", line 1133, in run
    value = future.result()
  File "/usr/local/lib/python2.7/dist-packages/tornado/concurrent.py", line 261, in result
    raise_exc_info(self._exc_info)
  File "/usr/local/lib/python2.7/dist-packages/tornado/gen.py", line 307, in wrapper
    result = func(*args, **kwargs)
  File "/home/odroid/code/cameranetwork/CameraNetwork/server.py", line 978, in handle_seek
    query_date = seek_time.date()
AttributeError: 'int' object has no attribute 'date'
```

**Comment by OmerShubi** [comment]
Created by https://github.com/Addalin/cameranetwork/blob/02ffc27cc45250f520f333b2f748cec080a9158a/CameraNetwork/gui/enaml_files/docks.enaml#L464
And relates to seek button that creates the map in GUI. commenting line disables the error.

**Comment by Addalin** [comment]
@scaperex please add a screenshot of the GUI
@Addalin check with Amit, and ask if this is related to space carving. Is it possible to do space carving when this issue is still open?

**Comment by OmerShubi** [comment]
Here it is @Addalin 
![reproduction_issue#8](https://user-images.githubusercontent.com/28459495/67298784-68441280-f4f4-11e9-8960-11a989e00dfb.png)

**Comment by OmerShubi** [comment]
Map works in GUI. pymap3d=1.1.1 is required.
